name: CI/CD Pipeline

on:                    
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t roua21/web-api-prod:latest ./app
          docker push roua21/web-api-prod:latest

      - name: Setup kubeconfig
        run: bash ./setup-kubeconfig.sh
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s-resources/web-api-namespace.yaml
          kubectl apply -f k8s-resources/metallb-config.yaml
          kubectl apply -f k8s-resources/traefik-lb.yaml
          kubectl apply -f k8s-resources/web-api-deployment.yaml
          kubectl apply -f k8s-resources/web-api-service.yaml
          kubectl apply -f k8s-resources/web-api-ingress.yaml
